# Generated by Django 3.1.7 on 2021-03-16 06:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAnalysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_agent', models.CharField(max_length=200)),
                ('user_cookie', models.CharField(max_length=100)),
                ('access_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('leave_time', models.DateTimeField(blank=True, null=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('video_relation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='video.videorelation')),
            ],
            options={
                'db_table': 'UserAnalysis',
            },
        ),
        migrations.CreateModel(
            name='ActionAnalysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(max_length=10)),
                ('action_time', models.TimeField(blank=True, null=True)),
                ('story_end_time', models.TimeField(blank=True, null=True)),
                ('popup_btn_flg', models.BooleanField(default=False)),
                ('switch_video', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='video.video')),
                ('tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='video.tag')),
                ('user_analysis', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='view.useranalysis')),
            ],
            options={
                'db_table': 'ActionAnalysis',
            },
        ),
    ]
