# Generated by Django 3.1.7 on 2021-03-16 06:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import video.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project')),
            ],
            options={
                'db_table': 'VideoRelation',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(null=True, upload_to=video.models.get_upload_to)),
                ('three_dimensional_flg', models.BooleanField(default=False)),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('video_relation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video.videorelation')),
            ],
            options={
                'db_table': 'Video',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('action_type', models.CharField(max_length=20)),
                ('url', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('story_start_flame', models.IntegerField(blank=True, default=0, null=True)),
                ('popup_type', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('popup_img', models.FileField(blank=True, null=True, upload_to=video.models.get_popup_upload_to)),
                ('popup_text', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('popup_btn_text', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('popup_btn_url', models.URLField(blank=True, default='', max_length=100, null=True)),
                ('x_coordinate', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('y_coordinate', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('width', models.DecimalField(decimal_places=2, max_digits=5)),
                ('height', models.DecimalField(decimal_places=2, max_digits=5)),
                ('display_frame', models.IntegerField()),
                ('hide_frame', models.IntegerField()),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('story_next_video', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='story_next_video', to='video.videorelation')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video.video')),
            ],
            options={
                'db_table': 'Tag',
            },
        ),
        migrations.CreateModel(
            name='EndTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=100)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video.video')),
            ],
            options={
                'db_table': 'EndTag',
            },
        ),
    ]
