# Generated by Django 3.1.7 on 2021-03-26 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='x_coordinate',
            new_name='left',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='y_coordinate',
            new_name='top',
        ),
    ]
